"""add brand and category to products

Revision ID: c021c6c8990c
Revises: 036b7ce135a9
Create Date: 2026-08-24 12:59:11.048716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c021c6c8990c'
down_revision: Union[str, Sequence[str], None] = '036b7ce135a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'category')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
